apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
    - name: nodewebapp
      image: slimpotatoboy/sit737-2025-prac5p-app:latest
      ports:
        - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always