version: '1'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
# command to health check the app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/add?n1=1&n2=2"]
      interval: 30s
      timeout: 10s
      retries: 3